# Generated by Django 3.1.7 on 2021-03-20 17:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Названиае события')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на событие')),
                ('createdAt', models.BigIntegerField(blank=True, null=True, verbose_name='Дата создания')),
                ('left', models.IntegerField()),
                ('tags', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'События',
                'verbose_name_plural': 'Событии',
            },
        ),
    ]
